version: '2'
services:

  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb:/etc/mysql/conf.d
    ports:
      - "3307:3306" #mariadb-port
    container_name: mariadb

  redis-cache:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis-cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-cache

  redis-queue:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis-queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis-socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-socketio

  frappe:
    volumes:
      - frappe-bench:/home/frappe/frappe-bench:rw
    build: .
    working_dir: /home/frappe/frappe-bench
    ports:
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    container_name: frappe

volumes:
  frappe-bench:
